### ISSUE TITLE
How do you rollback a transaction?

### ISSUE THREAD

**Issue by cscalfani** [WraithM/opaleye-trans#11]
I'm struggling to find a way to rollback a transactions. Any help would be greatly appreciated.

**Comment by wraithm** [comment]
If you throw an exception, the transaction should rollback.

**Comment by wraithm** [comment]
We use `withTransaction` under the hood:

https://hackage.haskell.org/package/postgresql-simple-0.5.2.1/docs/Database-PostgreSQL-Simple.html#v:withTransaction

**Comment by cscalfani** [comment]
Thanks for the quick reply. I apologize for not asking the question better.

I'd like to conditionally rollback a transaction while still returning information regarding the error.

My use case is I'm doing multiple SQL operations and one or more of them can fail. I'm collection a list of results and I'd like to Rollback the whole transaction if there is 1 or more errors. Then I'd like it to return the list of errors.

If I throw an exception, I cannot add a payload to the Exception.

**Comment by wraithm** [comment]
You can add a payload to the exception. You just need to define your own exception and catch it. Use the [Exception](https://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Exception.html#t:Exception) type class.

**Comment by cscalfani** [comment]
Thanks for the help, but after over an hour of searching, I cannot seem to find ANY Haskell Exceptions that have a payload. Sorry, but I'm a bit new to Haskell Exceptions.

Do you know of any example of an Exception with a payload?

**Comment by wraithm** [comment]
`ArrayException`: https://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Exception.html#t:ArrayException

That's an example, but there are plenty of examples. You really can do anything that has a `Typeable` and a `Show` instance.

You could do this, for example:
```
data MyDatabaseException = TableDoesNotExist String deriving Show
instance Exception MyDatabaseException

throwDatabaseException :: IO a
throwDatabaseException = throwIO (TableDoesNotExist "whatever_table_name")
```

**Comment by wraithm** [comment]
We also provide the `Opaleye.Trans.Exception` module in this package. That gives you some tools for making your own exception types and throwing them. Use the `throwError` function. If you run into any trouble using that module, let me know.

**Comment by cscalfani** [comment]
I'll check it out. Thanks!!
