### ISSUE TITLE
Combining postgres-simple transactions with opaleye-trans

### ISSUE THREAD

**Issue by cscalfani** [WraithM/opaleye-trans#13]
Is it possible to use a transaction from postgres-simple with an Opaleye transactions and if so, how?

Thanks.

**Comment by wraithm** [comment]
You can, but it's not recommended. You'll most likely get errors. If you wrap `withTransaction` around a call to `transaction`, you'll get a nested transaction in Postgres. That'll cause warnings on Postgres, but really they should be errors.

What are you trying to do that's causing trouble?

**Comment by cscalfani** [comment]
Makes sense. Not to happy with warnings or errors either way. It's too bad `withConnIO` is private.

**Comment by wraithm** [comment]
Just to be clear, the warnings/errors that I refer to are on the Postgresql side. You can't have nested transactions in postgresql. The reason why `withConnIO` is private is that the whole point of this library is to make it easy to avoid these nested transactions.
