### ISSUE TITLE
Add `MonadThrow` and `MonadCatch` instances from `exception` package.

### ISSUE THREAD

**Issue by utdemir** [WraithM/opaleye-trans#9]
Hey.

It would be really useful to provide a `MonadCatch` and `MonadThrow` instances (from `exceptions` package). 

Currently I have:

```
deriving instance MonadThrow m => MonadThrow (OpaleyeT m)
deriving instance MonadCatch m => MonadCatch (OpaleyeT m)
```

in my codebase, but orphan instances suck.

Only drawback would be introducing a new dependency, but `exceptions` is pretty light.

What do you think?

**Comment by wraithm** [comment]
Yeah! I'm not opposed to it at all.

I also just added the `Opaleye.Trans.Exception` module, which I'm somewhat on the fence about in terms of design. Check it out. I'd love some feedback.

Would you be willing to make a PR? I'm a little busy at the moment.

**Comment by wraithm** [comment]
Thanks! Closing based on #10. I'll bump the version number and add this to hackage some time soon! Remind me if I don't.

**Comment by wraithm** [comment]
Version 0.4.2 uploaded to hackage!
